server:
  port: 9999
  servlet:
    context-path: /agriLoan
spring:
  #   数据源配置
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.7.20:3306/credit_through_train?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: 'Aa@123456'
  # redis
  redis:
    host: 192.168.7.41
    port: 6379
    database: 7
    password: ovit
    timeout: 50000


