spring:
  # Api文档
  swagger:
    groups:
      demo:
        title: 湖北省信贷直通车
        version: v2.0
        basePackage: com.ovit.agriLoan
        description: 湖北省信贷直通车
        contact:
          name: 湖北省信贷直通车
